/**
 * This script will be included in the `pkg/hydrate.js` generated by `wasm-pack build`
 * via the `#[wasm_bindgen(module = "/src/hydrate.js")]` attribute in `src/client.rs`,
 * and should be served as `/.uibeam/hydrate.js`.
 * 
 * It is responsible for hydrating the UI components on the client side.
 */

/** dummy export to ensure this file is included in the final pkg/hydrate.js by wasm-pack */
export function ensure_hydrate_js_is_included() {};

(async () => {
  // self-import to access the hydraters by their name strings
  const { default: init, ...hydraters } = await import('/.uibeam/hydrate.js');
  
  await init();
  
  document.querySelectorAll('[data-uibeam-hydrater]').forEach((container) => {
    const hydraterName = container.getAttribute('data-uibeam-hydrater');
    if (!hydraterName) {
      console.error(`[uibeam] no hydrater name: ${container}`);
      return;
    }
    const hydrater = hydraters[hydraterName];
    if (!hydrater) {
      console.error(`[uibeam] no hydrater found for name '${hydraterName}': ${container}`);
      return;
    }
    
    const propsStr = container.getAttribute('data-uibeam-props');
    if (!propsStr) {
      console.error(`[uibeam] no props string: ${container}`);
      return;
    }
    let props = null;
    try {
      props = JSON.parse(propsStr);
    } catch (e) {
      console.error(`[uibeam] failed to parse props JSON '${propsStr}': ${e}`);
      return;
    }
    if (!props) {
      console.error(`[uibeam] no props parsed: ${container}`);
      return;
    }
    
    try {
      hydrater(props, container);
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      console.error(`[uibeam] failed to hydrate with '${hydraterName}' and props '${JSON.stringify(propsStr)}': ${message}`);
    }
  });
})();
