#![cfg_attr(docsrs, feature(doc_cfg))]
/* execute doc tests for sample codes in README */
#![cfg_attr(all(doc, not(docsrs)), doc = include_str!("../../README.md"))]

//! <div align="center">
//!     <h1>
//!         UIBeam
//!     </h1>
//!     <p>
//!         A struct-based, JSX-style Web UI library for Rust
//!     </p>
//! </div>
//!
//! <div align="right">
//!     <a href="https://github.com/ohkami-rs/uibeam/blob/main/LICENSE"><img alt="License" src="https://img.shields.io/crates/l/uibeam.svg" /></a>
//!     <a href="https://github.com/ohkami-rs/uibeam/actions"><img alt="CI status" src="https://github.com/ohkami-rs/uibeam/actions/workflows/CI.yml/badge.svg"/></a>
//!     <a href="https://crates.io/crates/uibeam"><img alt="crates.io" src="https://img.shields.io/crates/v/uibeam" /></a>
//! </div>
//!
//! - `UI!` : JSX-style template syntax with compile-time checks
//! - `Beam` : Component system based on Rust structs
//!
//! ## Features
//!
//! - Struct-based component model with minimal macro usage. (just `UI!` amd `#[client]`)
//! - Client components via island architecture in Wasm. (See *Client Component* section below)
//! - Best effort to generate efficient code for template rendering with less redundant memory allocation.
//!
//! Additionally, HTML completions and hovers in `UI!` by VSCode extension. (search`uibeam` in the extension marketplace)
//!
//! ![](https://github.com/ohkami-rs/uibeam/raw/HEAD/support/vscode/assets/completion.png)

#[cfg(all(hydrate, not(feature = "client")))]
compile_error!("`hydrate` cfg must be specified only when `client` feature is enabled");
#[cfg(all(hydrate, not(target_arch = "wasm32")))]
compile_error!("`hydrate` cfg must be specified only when compiling to Wasm");

/* for `UI!` use in this crate itself */
extern crate self as uibeam;

#[cfg_attr(docsrs, doc(cfg(feature = "client")))]
#[cfg(feature = "client")]
pub mod client;
#[cfg(feature = "__integration__")]
mod integration;
mod bound;

#[doc(hidden)]
#[cfg(feature = "client")]
pub use bound::{Client, IslandBoundary, render_in_island};
#[doc(hidden)]
pub use bound::{Server, render_on_server};
#[cfg_attr(docsrs, doc(cfg(feature = "client")))]
#[cfg(feature = "client")]
pub use client::signals::{Signal, Computed, Effect, EffectScope};
pub use uibeam_html::escape;
pub use uibeam_macros::UI;
#[cfg_attr(docsrs, doc(cfg(feature = "client")))]
#[cfg(feature = "client")]
pub use uibeam_macros::client;

use std::borrow::Cow;
#[cfg(feature = "client")]
use client::hydrate::{NodePath, Reactivity};

#[doc(hidden)]
#[allow(non_camel_case_types)]
/// automatically introduced by `#[client]`
pub trait client_attribute<T> {
    fn new(value: T) -> Self;
}

/// # `UI` - UIBeam's template representation
///
/// Generated by [ `UI!` ](macro@UI), and serialized into `Cow<'static, str>` by [`shoot`] function.\
/// See `UI!` for more details.
pub struct UI {
    template: Cow<'static, str>,
    #[cfg(hydrate)]
    reactivities: Vec<(NodePath, Reactivity)>,
);

/// # `Beam` - UIBeam's component system
///
/// <br>
///
/// ## Usage
///
/// When `StructName` implements `Beam`, `<StructName />` or `<StructName></StructName>`
/// are available in [ `UI!` ](macro@UI):
///
/// - `<StructName></StructName>` **requires** the struct to have `children`
///   field. The 0 or more children nodes are passed to `children` as `UI`.
/// - Attributes are interpreted as the struct's fields. Literals are
///   passed as `(it).into()`, and `{any expression}`s are passed directly.
///
/// See [ `UI!` ](macro@UI)'s doc for more details on it.
///
/// <br>
///
/// ---
///
/// <br>
///
/// ```jsx
/// <Struct a="1" b={"2".to_string()} />
///
/// // generates
///
/// Struct {
///     a: ("1").into(),
///     b: "2".to_string(),
/// }
/// ```
///
/// <br>
///
/// ---
///
/// <br>
///
/// ```jsx
/// <Struct a="1" b={"2".to_string()}>
///     <p>"hello"</p>
/// </Struct>
///
/// // generates
///
/// Struct {
///     a: ("1").into(),
///     b: "2".to_string(),
///     children: /* a `UI` representing `<p>hello</p>` */
/// }
/// ```
///
/// <br>
///
/// ---
///
/// <br>
///
/// ## Example
///
/// ```no_run
/// use uibeam::{UI, Beam};
///
/// struct MyComponent {
///     name: String,
///     age: u8,
/// }
///
/// impl Beam for MyComponent {
///     fn render(self) -> UI {
///         UI! {
///             <div>
///                 <p>"My name is "{self.name}</p>
///                 <p>"My age is "{self.age}</p>
///             </div>
///         }
///     }
/// }
///
/// let ui = UI! {
///     <h1>"Hello, Beam!"</h1>
///     <MyComponent name="Alice" age=30 />
/// };
/// let html = uibeam::shoot(ui);
/// println!("{}", html);
/// ```
pub trait Beam<Kind: bound::BeamKind = Server> {
    fn render(self) -> UI;
}

#[cfg(not(all(feature = "client", hydrate)))]
#[inline(always)]
pub fn shoot(ui: UI) -> Cow<'static, str> {
    ui.0
}

#[cfg(all(feature = "client", hydrate))]
#[doc(hidden)]
/// generate hydrated island node.
pub fn shoot(ui: UI) -> ::web_sys::Node {
    use ::web_sys::{HtmlTemplateElement, window};
    use ::wasm_bindgen::JsCast;
    
    thread_local! {
        static CACHED_TEMPLATE: ::web_sys::HtmlTemplateElement = {
            let t = window().unwrap().document().unwrap().create_element("template").unwrap();
            t.set_inner_html(ui.template);
            t.unchecked_into()
        };
    }
    
    let island_root: ::web_sys::DocumentFragment = CACHED_TEMPLATE.with(|t| {
        t.content().clone_node(true).unechecked_into()
    });
    
    for (path, rs) in self.reactivities {
        let node = path.traverse().expect("invalid path");
        for r in rs {
            r.apply_in_island(island_root, node);
        }
    }
    
    island_root.unchecked_into()
}

impl FromIterator<UI> for UI {
    #[inline]
    fn from_iter<T: IntoIterator<Item = UI>>(iter: T) -> Self {
        let mut result = String::new();
        for item in iter {
            result.push_str(&item.0);
        }
        UI(Cow::Owned(result))
    }
}

impl UI {
    pub const EMPTY: UI = UI(Cow::Borrowed(""));

    #[inline(always)]
    pub fn concat<const N: usize>(uis: [UI; N]) -> Self {
        match uis.len() {
            0 => UI::EMPTY,
            1 => unsafe {
                // SAFETY:
                // * original `uis` is moved to this function,
                //   so never used again by anyone
                // * `ManuallyDrop` prevents double free
                //   and returned `Self`'s destructor will free this memory
                std::ptr::read(
                    // SAFETY:
                    // * Here `uis` is `[UI; 1]`
                    // * `[T; 1]` has the same layout as `T`
                    // * `ManuallyDrop<T>` has the same layout as `T`
                    &*std::mem::ManuallyDrop::new(uis) as *const [UI] as *const [UI; 1]
                        as *const UI,
                )
            },
            _ => {
                let mut buf = String::with_capacity(uis.iter().map(|ui| ui.template.len()).sum());
                for ui in uis {
                    buf.push_str(&ui.0);
                }
                UI(Cow::Owned(buf))
            }
        }
    }
}

#[doc(hidden)]
pub struct DynamicExpr<T>(
    #[cfg(not(hydrate))]
    pub T,
    #[cfg(hydrate)]
    /// to handle reactivity
    pub Box<dyn Fn() -> T>,
);

#[doc(hidden)]
pub enum Dynamic {
    /// - `class={foo}`
    /// - `checked={true}`
    /// - `width={100}`
    Attribute(DynamicExpr<AttributeValue>),
    /// e.g. `onclick={move |_| console::log_1(&"clicked".into())}`
    #[cfg(feature = "client")]
    EventHandler(Box<dyn Fn(::web_sys::Event)>),
    /// ```UI
    /// <p>"Count: "{count.get()}</p>
    /// ```
    Text(DynamicExpr<Cow<'static str>>),
    /// directly emmbeded string, intentionally skipping HTML-escape:
    /// 
    /// ```UI
    /// <div>
    ///     unsafe { reliable_html_string() }
    /// </div>
    /// ```
    UnsafeRawHtmlString(DynamicExpr<Cow<'static, str>>),
    /// ```UI
    /// <div>
    ///     {if condition {
    ///         <p>"condition holds!"</p>
    ///     } else if condition2 {
    ///         <p>"another condition holds!"</p>
    ///     } else {
    ///         <p>"no conditions hold"</p>
    ///     }}
    /// </div>
    /// ```
    If {
        condition: DynamicExpr<bool>,
        then: DynamicExpr<UI>,
        else_if: Option<Vec<(DynamicExpr<bool>, DynamicExpr<UI>)>>,
        else: Option<DynamicExpr<UI>>,
    },
    /// ```UI
    /// <ul>{for name in ["abc", "def", "ghi"] {
    ///     <li key={name}>"name: "{name}</li>
    /// }}</ul>
    /// ```
    For {
        iterator: DynamicExpr<Vec<Box<dyn Any>>>,
        item_fn: Box<dyn Fn(Box<dyn Any>) -> UI>,
    },
}

#[cfg(feature = "client")]
const _: () = {
    macro_rules! EventHandler {
        ($( $EventType:ty { $($listenername:ident),+ $(,)? } )*) => {
            $(
                impl AttributeValue {
                    #[doc(hidden)]
                    pub fn $listenername(handler: impl Fn($EventType) -> ()) -> Self {
                        Self::EventHandler(Box::new(move |event: web_sys::Event| {
                            handler(web_sys::Event::from(event))
                        }))
                    }
                }
            )*
        };
    }
    EventHandler! {
        web_sys::Event {
            onafterprint,
            onbeforeprint,
            onbeforeunload,
            onbeforematch,
            onchange,
            onfullscreenchange,
            onfullscreenerror,
            onload,
            onscroll,
            onscrollend,
            onoffline,
            ononline,
        }
        web_sys::AnimationEvent {
            onanimationcancel,
            onanimationend,
            onanimationiteration,
            onanimationstart,
        }
        web_sys::ClipboardEvent {
            oncopy,
            oncut,
            onpaste,
        }
        web_sys::CompositionEvent {
            oncompositionend,
            oncompositionstart,
            oncompositionupdate,
        }
        web_sys::FocusEvent {
            onblur,
            onfocus,
            onfocusin,
            onfocusout,
        }
        web_sys::InputEvent {
            oninput,
            onbeforeinput,
        }
        web_sys::KeyboardEvent {
            onkeydown,
            onkeyup,
        }
        web_sys::MouseEvent {
            onauxclick,
            oncontextmenu,
            ondblclick,
            onmousedown,
            onmouseenter,
            onmouseleave,
            onmousemove,
            onmouseout,
            onmouseover,
            onmouseup,
        }
        web_sys::PointerEvent {
            onclick,
            ongotpointercapture,
            onlostpointercapture,
            onpointercancel,
            onpointerdown,
            onpointerenter,
            onpointerleave,
            onpointermove,
            onpointerout,
            onpointerover,
            onpointerrawupdate,
            onpointerup,
        }
        web_sys::TouchEvent {
            ontouchcancel,
            ontouchend,
            ontouchmove,
            ontouchstart,
        }
        web_sys::TransitionEvent {
            ontransitioncancel,
            ontransitionend,
            ontransitionrun,
            ontransitionstart,
        }
        web_sys::UiEvent {
            onresize,
        }
        web_sys::WheelEvent {
            onwheel,
        }
    }
};

#[doc(hidden)]
pub enum AttributeValue {
    Text(Cow<'static, str>),
    Integer(isize),
    Boolean(bool),
}
#[doc(hidden)]
const _: () = {
    impl From<bool> for AttributeValue {
        #[inline(always)]
        fn from(value: bool) -> Self {
            AttributeValue::Boolean(value)
        }
    }

    impl From<&'static str> for AttributeValue {
        fn from(value: &'static str) -> Self {
            AttributeValue::Text(value.into())
        }
    }
    impl From<String> for AttributeValue {
        #[inline(always)]
        fn from(value: String) -> Self {
            AttributeValue::Text(value.into())
        }
    }
    impl From<Cow<'static, str>> for AttributeValue {
        fn from(value: Cow<'static, str>) -> Self {
            AttributeValue::Text(value)
        }
    }

    impl From<i8> for AttributeValue {
        fn from(it: i8) -> Self {
            AttributeValue::Integer(it.into())
        }
    }
    impl From<i16> for AttributeValue {
        fn from(it: i16) -> Self {
            AttributeValue::Integer(it.into())
        }
    }
    impl From<i32> for AttributeValue {
        #[inline(always)]
        fn from(it: i32) -> Self {
            AttributeValue::Integer(it.into())
        }
    }
    impl From<i64> for AttributeValue {
        fn from(it: i64) -> Self {
            AttributeValue::Integer(it.try_into().unwrap_or_else(|_| panic!("{}", &too_large_error_message(it)))
        }
    }
    impl From<isize> for AttributeValue {
        fn from(it: isize) -> Self {
            AttributeValue::Integer(it)
        }
    }
    impl From<u8> for AttributeValue {
        fn from(it: u8) -> Self {
            AttributeValue::Integer(it.into())
        }
    }
    impl From<u16> for AttributeValue {
        fn from(it: u16) -> Self {
            AttributeValue::Integer(it.into())
        }
    }
    impl From<u32> for AttributeValue {
        #[inline(always)]
        fn from(it: u32) -> Self {
            AttributeValue::Integer(it.try_into()
                .unwrap_or_else(|_| panic!("{}", &too_large_error_message(it)))
        }
    }
    impl From<u64> for AttributeValue {
        fn from(it: u64) -> Self {
            AttributeValue::Integer(
                it.try_into()
                    .unwrap_or_else(|_| panic!("{}", &too_large_error_message(it))),
            )
        }
    }
    impl From<usize> for AttributeValue {
        fn from(it: usize) -> Self {
            AttributeValue::Integer(
                it.try_into()
                    .unwrap_or_else(|_| panic!("{}", &too_large_error_message(it))),
            )
        }
    }
    #[cold]
    #[inline(never)]
    fn too_large_error_message(int: impl std::fmt::Display) -> String {
        format!("can't use `{int}` as attribute value: too larger")
    }
};

#[cfg(not(hydrate))]
const _: () = {
    enum Interpolation {
        Attribute(AttributeValue),
        #[cfg(feature = "client")]
        EventHandler,
        Text(DynamicExpr<Cow<'static str>>),
        UnsafeRawHtmlString(DynamicExpr<Cow<'static, str>>),
        Children(UI),
    }
    impl From<Dynamic> for Interpolation {
        fn from(dynamic: Dynamic) -> Interpolation {
            match dynamic {
                Dynamic::Attribute(x) => Interpolation::Attribute(x),
                #[cfg(feature = "client")]
                Dynamic::EventHandler(_) => Interpolation::EventHandler,
                Dynamic::Text(x) => Interpolation::Text(x),
                Dynamic::UnsafeRawHtmlString(x) => Interpolation::UnsafeRawHtmlString(x),
                Dynamic::If { condition, then, else_if, else } => Interpolation::Children({
                    if condition {
                        then
                    } else if let Some(else_if) = else_if
                        .into_iter()
                        .flatten()
                        .find_map(|(cond, ui)| cond.then_some(ui))
                    {
                        else_if
                    } else if let Some(else) = else {
                        else
                    } else {
                        UI::EMPTY
                    }
                }),
                Dynamic::For { iterator, item_fn } => Interpolation::Children({
                    iterator.into_iter().map(item_fn).collect()
                })
            }
        }
    }
    impl Interpolation {
        fn len(&self) -> usize {
            match self {
                Self::Attribute(x) => match x {
                    AttributeValue::Text(text) => {
                        1/* " */ + text.len() * 2/* escape margin */ + 1 /* " */
                    }
                    AttributeValue::Integer(_) => {
                        1/* " */ + 4/* max-level length of typically used integer attribute values */ + 1 /* " */
                    }
                    AttributeValue::Boolean(_) => {
                        0 /* never push any tokens */
                    }
                }
                #[cfg(feature = "client")]
                Self::EventHandler => 0, /* never push any tokens */
                Self::Text(x) => x.len() * 2, /* espace margin */
                Self::UnsafeRawHtmlString(x) => x.len(),
                Self::Children(x) => x.template.len(),
            }
        }
    }
    
    impl UI {
        /// tends to be used by the `UI!` macro internally.
        ///
        /// ## SAFETY
        ///
        /// 1. `template_pieces` must have 0 = N or exactly `N + 1` pieces.
        /// 2. `template_pieces` must be concatenated into
        ///    a valid HTML string with any `interpolations` in place.
        /// 3. Each piece in `template_pieces` must be already HTML-escaped.
        ///    (intended to be escaped in `UI!` macro internally /
        ///    `new_unchecked` itself does not check or escape)
        #[doc(hidden)]
        pub unsafe fn new_unchecked<const N: usize>(
            template_pieces: &'static [&'static str],
            interpolations: [Dynamic; N],
        ) -> Self {
            debug_assert!(
                {
                    let len = template_pieces.len();
                    (len == 0 && N == 0) || len == N + 1
                }
                "invalid template_pieces.len(): {len} where N = {N}: template_pieces must have 0 = N or exactly N + 1 pieces"
            );
            
            macro_rules! delete_entire_attribute {
                () => {                    
                    let Some(sp) = buf.rfind(|c| {
                        matches!(c, ' ' | '\t' | '\n' | '\x0C' | '\r')
                    }) else {
                        unreachable!("`buf` is a part of a valid HTML string and then at least one whitespace exists before an attribute name")
                    };
                    buf.truncate(sp);
                };
            }
            
            match template_pieces.len() {
                0 => UI::EMPTY,
                1 => UI(Cow::Borrowed(template_pieces[0])),
                _ => {
                    let interpolations = interpolations.map(Interpolation::from);
                    
                    let mut buf = String::with_capacity({
                        let mut size = 0;
                        for piece in template_pieces {
                            size += piece.len();
                        }
                        for i in &interpolations {
                            size += match i {
                                Interpolation::Attribute(value) => match value {
                                    AttributeValue::Text(text) => {
                                        1/* " */ + text.len() + 1 /* " */
                                    }
                                    AttributeValue::Integer(_) => {
                                        1/* " */ + 4/* max-level length of typically used integer attribute values */ + 1 /* " */
                                    }
                                    AttributeValue::Boolean(_) => {
                                        0 /* never push any tokens */
                                    }
                                }
                                Interpolation::EventHandler => {
                                    0 /* never push any tokens in template rendering */
                                }
                                Interpolation::Text(text) => text.len() * 2, /* sufficient size even when taking HTML-espaces into consideration */
                                Interpolation::UnsafeRawHtmlString(raw) => raw.len(),
                                Interpolation::Children(ui) => ui.template.len(),
                            }
                        }
                        size
                    });
                    
                    for i in 0..N {
                        buf.push_str(template_pieces[i]);
                        match &interpolations[i] {
                            Interpolation::EventHandler => {
                                delete_entire_attribute!();
                            }
                            Interpolation::Text(text) => {
                                buf.push_str(&escape(text));
                            }
                            Interpolation::UnsafeRawHtmlString(s) => {
                                buf.push_str(&s);
                            }
                            Interpolation::Children(ui) => {
                                buf.push_str(&ui.template);
                            }
                            Interpolation::Attribute(value) => {
                                // ```in UI!{}
                                // <div class={}
                                //            |
                                //            /-- this `value` is here
                                // ```
                                debug_assert!(buf.ends_with('='));
                                match value {
                                    AttributeValue::Text(text) => {
                                        buf.push('"');
                                        buf.push_str(&escape(text));
                                        buf.push('"');
                                    }
                                    AttributeValue::Integer(int) => {
                                        // here we don't need to escape
                                        buf.push('"');
                                        buf.push_str(&int.to_string());
                                        buf.push('"');
                                    }
                                    AttributeValue::Boolean(boolean) => {
                                        // if `boolean` is `true`, we'll just leave the attribute name :
                                        //
                                        // ```in UI!{}
                                        // <input type="checkbox" checked={true}
                                        //
                                        // // to
                                        //
                                        // <input type="checkbox" checked
                                        // ```
                                        //
                                        // if `boolean` is `false`, we'll remove up to the attribute name :
                                        //
                                        // ```in UI!{}
                                        // <input type="checkbox" checked={false}
                                        //
                                        // // to
                                        //
                                        // <input type="checkbox"
                                        // ```
                                        //
                                        // this can be done by removing after the last whitespace of current `buf`
                                        // (because the SAFETY contract encusres `buf` is a part of a valid HTML string
                                        // and then at least one whitespace exists before an attribute name)
                                        let Some('=') = buf.pop() else { unreachable!() };
                                        if !*boolean {
                                            delete_entire_attribute!();
                                        }
                                    }
                                }
                            }
                        }
                    }
                    buf.push_str(template_pieces[N]);
                    UI(Cow::Owned(buf))
                }
            }
        }
    }
};

#[cfg(hydrate)]
impl UI {
    /// This is needed in `Reactivity::{If, For}::apply_in_island`, especially `For`'s,
    /// that need ability to generate new `UI`s of each item based on conditions or lists.
    /// 
    /// ## SAFETY
    /// 
    /// `skelton_template` MUST be valid HTML that:
    /// 
    /// - skips rendering entire attribute if its value is reactive.
    /// - skips rendering `if` or `for`.
    #[doc(hidden)]
    pub unsafe fn new_unchecked_in_island(
        island_root: &Node
        skelton_template: &'static str,
        reactivities: Vec<(NodePath, Reactivity)>,
    ) -> Self {
        let node = html_from_string(skelton_template);
        reactivities.for_each(|(path, r)| {
            let target_node = path.traverse(island_root).expect("NodePath traversal failed");
            r.apply_in_island(island_root);
        });
        Self(node)
    }
}

#[cfg(not(feature = "client"))]
#[cfg(test)]
mod test {
    use super::*;

    /* compiles */
    fn __assert_impls__() {
        fn is_children<X, C: IntoChildren<X>>(_: C) {}

        fn dummy_ui() -> UI {
            todo!()
        }

        is_children(dummy_ui());
        is_children(Some(dummy_ui()));
        is_children(None::<UI>);
        is_children((1..=3).map(|_| dummy_ui()));
    }

    #[test]
    fn test_ui_new_unchecked() {
        assert_eq!((unsafe { UI::new_unchecked(&[], []) }).0, r##""##);

        assert_eq!(
            (unsafe { UI::new_unchecked(&[r##"<div>"##,], []) }).0,
            r##"<div>"##
        );

        assert_eq!(
            (unsafe {
                UI::new_unchecked(
                    &[r##"<div class="##, r##"></div>"##],
                    [Dynamic::Attribute(AttributeValue::from("foo"))],
                )
            })
            .0,
            r##"<div class="foo"></div>"##
        );

        assert_eq!(
            (unsafe {
                UI::new_unchecked(
                    &[r##"<article class="##, r##">"##, r##"</article>"##],
                    [
                        Dynamic::Attribute(AttributeValue::from("main-article")),
                        Dynamic::Children(IntoChildren::<_, true>::into_children(
                            (1..=3_usize).map(|i| {
                                UI::new_unchecked(
                                    &[r##"<p>i="##, r##"</p>"##],
                                    [Dynamic::Children(
                                        IntoChildren::<_, true>::into_children(i.to_string()),
                                    )],
                                )
                            }),
                        )),
                    ],
                )
            })
            .0,
            r##"<article class="main-article"><p>i=1</p><p>i=2</p><p>i=3</p></article>"##
        );
    }

    #[test]
    fn test_ui_interploate_expression() {
        let ui = UI! {
            {"an expression"}
        };
        assert_eq!(shoot(ui), r##"an expression"##);

        let ui = UI! {
            <p>"a text node"</p>
        };
        assert_eq!(shoot(ui), r##"<p>a text node</p>"##);

        let ui = UI! {
            <p>{"an expression"}</p>
        };
        assert_eq!(shoot(ui), r##"<p>an expression</p>"##);

        let ui = UI! {
            <div class="foo">
                <p>"hello"</p>
            </div>
        };
        let ui = UI! {
            <div class="bar">
                {ui}
            </div>
        };
        assert_eq!(
            shoot(ui),
            r##"<div class="bar"><div class="foo"><p>hello</p></div></div>"##
        );

        struct Layout {
            children: UI,
        }
        impl Beam for Layout {
            fn render(self) -> UI {
                UI! {
                    <html>
                        <head>
                            <meta charset="UTF-8">
                        </head>
                        <body>
                            {self.children}
                        </body>
                    </html>
                }
            }
        }

        assert_eq!(
            /* automatic doctype insertion */
            shoot(UI! { <Layout></Layout> }),
            r##"<!DOCTYPE html><html><head><meta charset="UTF-8"/></head><body></body></html>"##
        );

        assert_eq!(
            /* automatic doctype insertion */
            shoot(UI! { <Layout><h1>"Hello, Beam!"</h1></Layout> }),
            r##"<!DOCTYPE html><html><head><meta charset="UTF-8"/></head><body><h1>Hello, Beam!</h1></body></html>"##
        );

        let content = UI! {
            <h1>"Hello, Beam!"</h1>
        };
        assert_eq!(
            /* automatic doctype insertion */
            shoot(UI! { <Layout>{content}"[test]"</Layout> }),
            r##"<!DOCTYPE html><html><head><meta charset="UTF-8"/></head><body><h1>Hello, Beam!</h1>[test]</body></html>"##
        );
    }
}
